const views={
studio:{title:'From an idea to a tested agent.',body:'Design agents around a clear task. Connect their knowledge and tools, compose a workflow and evaluate it before release.',features:['Agent and workflow builder','Model and tool configuration','Evaluations, versions and release review'],app:'Studio / Supplier review',rows:[['Research agent','Gather evidence'],['Contract analyst','Review supplied terms'],['Review gate','Human approval']],action:'Run simulated evaluation',result:'Demo evaluation complete: source references attached, review gate preserved. No live models or tools were called.'},
enterprise:{title:'A shared workspace. Clear boundaries.',body:'Give teams a place to use agents, find knowledge and review outcomes. Give administrators visibility over access, activity and spend.',features:['Knowledge search with source references','Workspace permissions and approval policies','Audit history, usage and cost controls'],app:'Enterprise / Review queue',rows:[['Supplier review','Awaiting approval'],['Workspace access','Procurement team'],['External actions','Require approval']],action:'Review simulated request',result:'Demo review recorded. The draft is marked reviewed in this preview only. No purchase, renewal or external message was sent.'},
marketplace:{title:'Extend the platform around your work.',body:'Discover reusable agents, connectors and workflow packs. Review what they need before bringing them into your workspace.',features:['Curated agents and industry packs','Declared permissions and version history','Controlled installation and update review'],app:'Marketplace / Supplier review pack',rows:[['Package version','Concept 0.1'],['Access requested','Read supplied documents'],['External actions','None enabled']],action:'Preview permission review',result:'Permission preview: read contracts, spend and procurement policy. A workspace administrator would approve installation. This demo installs nothing.'}
};
function showProduct(key){const v=views[key];document.querySelectorAll('[data-product]').forEach(b=>{const selected=b.dataset.product===key;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected))});document.getElementById('product-detail').innerHTML=`<div><h3>${v.title}</h3><p>${v.body}</p><div class="feature-list">${v.features.map(x=>`<div>${x}</div>`).join('')}</div></div><div class="mini-app"><div class="mini-app-top"><b>${v.app}</b><span>Simulated</span></div><h4>${key==='enterprise'?'A decision with context':key==='marketplace'?'Know what you are enabling':'Define the workflow'}</h4>${v.rows.map(r=>`<div class="mini-row"><b>${r[0]}</b><span>${r[1]}</span></div>`).join('')}<button class="demo-btn" id="demo-action">${v.action}</button><p class="demo-state" id="demo-result" role="status"></p></div>`;document.getElementById('demo-action').onclick=e=>{document.getElementById('demo-result').textContent=v.result;e.target.disabled=true;e.target.textContent='Preview complete'}}
document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>showProduct(b.dataset.product));showProduct('studio');
const packs=[
{name:'Enterprise research',category:'business',label:'Knowledge & research',symbol:'Re',desc:'Turn scattered sources into a referenced brief.',roles:'Researcher, source reviewer and brief writer',input:'Supplied documents and approved knowledge sources',output:'A research brief with references, source conflicts and open questions',review:'A person checks source quality and conclusions before sharing.'},
{name:'Supplier review',category:'business',label:'Procurement & finance',symbol:'Su',desc:'Bring contract terms, spend and policy into one review.',roles:'Supplier reviewer, contract analyst and spend analyst',input:'Contracts, spend records and procurement policy',output:'A supplier brief with renewal considerations and policy exceptions',review:'Purchasing, contract changes and messages require human approval.'},
{name:'Service knowledge',category:'business',label:'People & customer teams',symbol:'Sk',desc:'Find approved answers and prepare helpful responses.',roles:'Policy assistant, onboarding guide and response drafter',input:'Approved policies, service guidance and supplied requests',output:'A referenced answer or response draft for the team',review:'A person reviews external replies and sensitive employee decisions.'},
{name:'Diligence & review',category:'industry',label:'Financial services',symbol:'Dr',desc:'Organise evidence for a structured diligence process.',roles:'Diligence coordinator, evidence reviewer and brief writer',input:'Supplied diligence documents and review criteria',output:'An evidence register, unresolved questions and draft findings',review:'Qualified reviewers make investment and compliance decisions.'},
{name:'Asset intelligence',category:'industry',label:'Industrial & energy',symbol:'Ai',desc:'Connect asset knowledge to maintenance planning.',roles:'Asset knowledge agent, maintenance planner and reviewer',input:'Asset manuals, supplied records and planning constraints',output:'A maintenance planning brief with references and missing information',review:'Authorised teams approve work plans; no equipment control is enabled.'},
{name:'Reliability & SRE',category:'industry',label:'Technology & telecom',symbol:'Sr',desc:'Add incident, change and capacity context when needed.',roles:'Incident investigator, change reviewer and capacity analyst',input:'Supplied incidents, change records, runbooks and capacity data',output:'An investigation timeline and suggested next checks',review:'Operators approve remediation. This extension does not define the core platform.'}
];
const dialog=document.getElementById('pack-dialog');
function renderPacks(filter='all'){document.getElementById('pack-grid').innerHTML=packs.map((p,i)=>({...p,i})).filter(p=>filter==='all'||p.category===filter).map(p=>`<article class="pack"><div class="pack-symbol">${p.symbol}</div><span class="pack-category">${p.label.toUpperCase()}</span><h3>${p.name}</h3><p>${p.desc}</p><button data-pack="${p.i}">Explore planned pack</button></article>`).join('');document.querySelectorAll('[data-pack]').forEach(b=>b.onclick=()=>{const p=packs[Number(b.dataset.pack)];document.getElementById('pack-content').innerHTML=`<p class="eyebrow">PLANNED PACK / ${p.label.toUpperCase()}</p><h2 id="pack-title">${p.name}</h2><p>${p.desc}</p><h4>Agent team</h4><p>${p.roles}.</p><h4>Context in</h4><p>${p.input}.</p><h4>Outcome out</h4><p>${p.output}.</p><h4>Human oversight</h4><p>${p.review}</p><a class="button" href="mailto:hello@jengara.ai?subject=${encodeURIComponent('Ribyos design partner: '+p.name)}">Discuss this workflow</a><p class="note">Concept only. No systems connected or agent execution.</p>`;dialog.showModal()})}
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b))});renderPacks(b.dataset.filter)});renderPacks();
